Algoritmo "ensinando"

Var

   option: real
   continue: caractere


Inicio

      escreval("Digite e tecle enter para aprender sobre os respectivos tópicos")
      escreval("===============================================================")


      escreval("[1] Básico do Portugol")
      escreval("[2]")
      escreval("[3]")
      escreval("[4]")
      escreval("[5]")
      escreval("[6]")
      escreval("[7]")
      escreval("[8]")
      escreval("[9]")
      escreval("[10]")
      escreval("[11]")
      escreval("[12]")
      escreval("[13]")
      escreval("[14]")
      escreval("[15]")

      Leia(option)

                  se (option = 1) então

                             escreval("Vamos começar com o básico então")
                             escreval("Primeiramente todo código em portugol deve conter 4 coisas")
                             escreval("1 - inicio, 2 - Var, 3 - Algoritmo e 4 - FimAlgoritmo")
                             escreval("Abrindo o programa visualg você verá como organizar esses elementos")
                             escreval("")
                             escreva("======================================================================")
                             escreval("")
                             escreval("existem váriaveis no portugol, assim como em qualquer outra linguagem")
                             escreval("Você pode criar váriaveis digitando uma palavra no campo -> Var do código")

                             escreva("Quer aprender mais sobre váriaveis, então tecle qualquer tecla.")
                             Leia(continue)

                             escreval("")
                             escreval("no campo var digite o seguinte -> Notas: real ")
                             escreval("Pornto, você criou uma várivel do tipo real no portugol")
                             escreval("Lembrando que váriais no portugol devem seguir regras")
                             escreval("1. devem ter nomes simples e óbvios")
                             escreval("2. não podem conter caracteres especiais")
                             escreval("3. o espaçamento deve ser feito com o uso de underline")
                             escreval("4. letras minúsculas sempre")

                             escreva("Quer aprender mais sobre váriaveis, então tecle qualquer tecla.")
                             Leia(continue)

                             escreval("Essas são as regras para se criar uma váriavel no portugol")
                             escreval("Existem 4 tipos de variáveis.")
                             escreval("1. caractere = texto")
                             escreval("2. inteiro = números inteiros")
                             escreval("3. real = númeors reais")
                             escreval("4. logico = falso ou verdadeiro")
                             escreval("   ")
                             escreval("Você pode digitar algo e salva-lo usando uma variável")
                             escreval("Mas, se você quer guadar um número na memória do computador...")
                             escreval("você precisa usar variáveis do tipo inteiro ou real")
                             escreval("   ")
                             escreval("Como salvar algo dentro de uma variável ???")
                             escreval("Digite assim leia'(x)', assim o o visualg vai permitir você...")
                             escreval("ddigitar um valor e salva-lo dentro de uma variável x, que precisa...")
                             escreval("ter sido criada antecipadamente no campo Var.")
                             escreval("   ")
                             escreval("Esse é o básico que você precisa para criar um programa no visualg")
                             escreval("")




                  FimSe


Fimalgoritmo